[build]
  command = "yarn run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "8.9.0"
  
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = ```
    public,
    max-age=0```
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
